Implemented polling method
mileszim/tempmail.js pull request #11
Opened 2016-07-01 17:38 UTC by giacomocerquone

Feature #3

2017-07-26 07:30 UTC, mileszim requested changes
Clean up your methods and compile into dist once finished. Thanks for the contribution!

2017-07-26 07:30 UTC, mileszim commented on README.md
> +var filterOptions = {
using `let` over `var` for object assignment is preferred

2017-07-26 07:30 UTC, mileszim commented on README.md
> +var filterOptionsTwo = {
using `let` over `var` for object assignment is preferred

2017-07-26 07:30 UTC, mileszim commented on README.md
> +var filterOptions = {
using `let` over `var` for object assignment is preferred

2017-07-26 07:30 UTC, mileszim commented on src/index.js
> +      return new Promise( (resolve, reject) => {
`return new Promise((resolve, reject) => {`

2017-07-26 07:30 UTC, mileszim commented on src/index.js
> +    async filterMessages(filterOptions) {
Any way to tidy up this method?

2018-02-10 10:34 UTC, giacomocerquone commented
You can just edit and add commits inside this PR instead of deleting and rewriting the code in another PR like you did!
I'm busy at the moment and I can't work on this.

2018-08-31 17:36 UTC, mileszim commented
Closing in favor of https://github.com/mileszim/tempmail.js/blob/master/src/index.js#L76-L89

2018-08-31 17:36 UTC, closed without merging